<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ApdSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('apds')->insert([
            // 🪖 HELM (Safety Helmet) – sesuai SPLN U2.006:2023 Lampiran Tabel Warna Helm
            [
                'jenis_id'        => 1,
                'nama_apd'        => 'Helm Safety Warna Putih (Manajemen, Engineer, dan Visitor)',
                'kode_apd'        => 'APD-001-PTH',
                'deskripsi'       => 'Melindungi kepala dari benturan benda jatuh dan kontak listrik bagi personel manajemen, engineer, dan tamu.',
                'gambar'          => 'apd/helm_putih.png',
                'bahan'           => 'ABS (Acrylonitrile Butadiene Styrene)',
                'warna'           => 'Putih (RAL 9010)',
                'ukuran'          => 'Universal (Adjustable)',
                'kemampuan'       => 'Tahan benturan vertikal dan arus listrik hingga 20.000 Volt.',
                'fungsi'          => 'Dilengkapi suspensi 6 titik dan chin strap. Warna putih digunakan untuk manajemen, engineer, dan visitor.',
                'standar'         => 'SPLN U2.006:2023; EN 397; ANSI Z89.1',
                'masa_penggunaan' => '4 tahun',
                'created_by'      => 1,
                'updated_by'      => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'jenis_id'        => 1,
                'nama_apd'        => 'Helm Safety Warna Merah (Pengawas K3 dan Pekerjaan)',
                'kode_apd'        => 'APD-001-MRH',
                'deskripsi'       => 'Digunakan oleh pengawas K3, pengawas pekerjaan, dan pengawas manuver untuk identifikasi mudah di lapangan.',
                'gambar'          => 'apd/helm_merah.png',
                'bahan'           => 'ABS (Acrylonitrile Butadiene Styrene)',
                'warna'           => 'Merah (RAL 3000)',
                'ukuran'          => 'Universal (Adjustable)',
                'kemampuan'       => 'Tahan panas dan benturan berat pada area kerja industri.',
                'fungsi'          => 'Helm merah sebagai tanda tanggung jawab pengawasan dan keselamatan kerja.',
                'standar'         => 'SPLN U2.006:2023; EN 397; ANSI Z89.1',
                'masa_penggunaan' => '4 tahun',
                'created_by'      => 1,
                'updated_by'      => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'jenis_id'        => 1,
                'nama_apd'        => 'Helm Safety Warna Biru (Pelaksana Pekerjaan)',
                'kode_apd'        => 'APD-001-BIR',
                'deskripsi'       => 'Digunakan oleh pelaksana pekerjaan di area proyek dan lapangan.',
                'gambar'          => 'apd/helm_biru.png',
                'bahan'           => 'HDPE (High Density Polyethylene)',
                'warna'           => 'Biru (RAL 5002)',
                'ukuran'          => 'Universal (Adjustable)',
                'kemampuan'       => 'Tahan benturan dan suhu kerja tinggi.',
                'fungsi'          => 'Warna biru digunakan oleh personel pelaksana utama pekerjaan sesuai SPLN.',
                'standar'         => 'SPLN U2.006:2023; EN 397; ANSI Z89.1',
                'masa_penggunaan' => '4 tahun',
                'created_by'      => 1,
                'updated_by'      => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'jenis_id'        => 1,
                'nama_apd'        => 'Helm Safety Warna Kuning (Mitra Kerja dan Magang)',
                'kode_apd'        => 'APD-001-KNG',
                'deskripsi'       => 'Dikenakan oleh mitra kerja (kontraktor) dan peserta magang sesuai pedoman SPLN.',
                'gambar'          => 'apd/helm_kuning.png',
                'bahan'           => 'HDPE (High Density Polyethylene)',
                'warna'           => 'Kuning (RAL 1026)',
                'ukuran'          => 'Universal (Adjustable)',
                'kemampuan'       => 'Melindungi kepala dari kejatuhan benda ringan dan panas sedang.',
                'fungsi'          => 'Warna kuning menandakan pekerja eksternal atau magang di lokasi kerja PLN.',
                'standar'         => 'SPLN U2.006:2023; EN 397; ANSI Z89.1',
                'masa_penggunaan' => '4 tahun',
                'created_by'      => 1,
                'updated_by'      => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],

            // 👓 KACAMATA PENGAMAN
            [
                'jenis_id'        => 2,
                'nama_apd'        => 'Kacamata Pengaman (Safety Glasses)',
                'kode_apd'        => 'APD-002',
                'deskripsi'       => 'Melindungi mata dari debu, partikel, dan percikan bahan kimia.',
                'gambar'          => 'apd/kacamata_default.png',
                'bahan'           => 'Polycarbonate',
                'warna'           => 'Transparan',
                'ukuran'          => 'Universal',
                'kemampuan'       => 'Anti gores, anti fog, dan UV protection.',
                'fungsi'          => 'Melindungi mata dari percikan, debu, dan radiasi UV.',
                'standar'         => 'ANSI Z87.1',
                'masa_penggunaan' => '2 tahun',
                'created_by'      => 1,
                'updated_by'      => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],

            // 👢 SAFETY SHOES – masa penggunaan 2 tahun
            [
                'jenis_id'        => 6,
                'nama_apd'        => 'Sepatu Safety S3 SRC (Anti Slip & Anti Tusuk)',
                'kode_apd'        => 'APD-003-S3',
                'deskripsi'       => 'Melindungi kaki dari benda berat, tusukan, dan lantai licin di area kerja.',
                'gambar'          => 'apd/safety_shoes_s3.png',
                'bahan'           => 'Kulit Full Grain + Sol PU/TPU',
                'warna'           => 'Hitam',
                'ukuran'          => '39–45',
                'kemampuan'       => 'Tahan benturan 200 Joule, anti tusuk, anti slip, dan tahan minyak.',
                'fungsi'          => 'Dilengkapi steel toe cap dan insole anti static (ESD protection).',
                'standar'         => 'EN ISO 20345; SPLN U2.006:2023',
                'masa_penggunaan' => '2 tahun',
                'created_by'      => 1,
                'updated_by'      => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'jenis_id'        => 6,
                'nama_apd'        => 'Sepatu Safety Dielectric (Tahan Listrik)',
                'kode_apd'        => 'APD-003-DLC',
                'deskripsi'       => 'Untuk pekerjaan listrik bertegangan tinggi (live line).',
                'gambar'          => 'apd/safety_shoes_dielectric.png',
                'bahan'           => 'Karet isolasi (Rubber Insulating)',
                'warna'           => 'Kuning',
                'ukuran'          => '39–44',
                'kemampuan'       => 'Tahan arus listrik hingga 18.000 Volt, anti slip, dan tahan minyak.',
                'fungsi'          => 'Tanpa logam, ringan, dan mudah dibersihkan.',
                'standar'         => 'EN ISO 20345; SPLN U2.006:2023',
                'masa_penggunaan' => '2 tahun',
                'created_by'      => 1,
                'updated_by'      => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],

            // 🧗 FULL BODY HARNESS – masa penggunaan 10 tahun
            [
                'jenis_id'        => 8,
                'nama_apd'        => 'Full Body Harness 5 Titik (Pekerjaan di Ketinggian)',
                'kode_apd'        => 'APD-004-5T',
                'deskripsi'       => 'Menahan tubuh agar tidak jatuh saat bekerja di tower, tiang, atau gardu.',
                'gambar'          => 'apd/full_body_harness_5titik.png',
                'bahan'           => 'Polyester Webbing + D-Ring Alloy Steel',
                'warna'           => 'Kuning & Hitam',
                'ukuran'          => 'All Size (Adjustable)',
                'kemampuan'       => 'Menahan beban hingga 140 kg; gaya jatuh maksimum 6 kN.',
                'fungsi'          => 'Dilengkapi dorsal, sternal, dan side D-rings serta lanyard absorber.',
                'standar'         => 'ANSI Z359.11; EN 361',
                'masa_penggunaan' => '10 tahun',
                'created_by'      => 1,
                'updated_by'      => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'jenis_id'        => 8,
                'nama_apd'        => 'Full Body Harness Double Lanyard Shock Absorber',
                'kode_apd'        => 'APD-004-DLY',
                'deskripsi'       => 'Menahan dan meredam energi jatuh bebas agar aman bagi pekerja.',
                'gambar'          => 'apd/harness_double_lanyard.png',
                'bahan'           => 'Polyamide Webbing + Hook Steel + Energy Absorber',
                'warna'           => 'Kuning',
                'ukuran'          => 'All Size (Adjustable)',
                'kemampuan'       => 'Mengurangi gaya jatuh hingga <6 kN; panjang total 2 meter.',
                'fungsi'          => 'Lanyard dilengkapi shock absorber dan dua pengait karabiner galvanis.',
                'standar'         => 'ANSI Z359.11; EN 361',
                'masa_penggunaan' => '10 tahun',
                'created_by'      => 1,
                'updated_by'      => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],

            // 🦺 LIFE JACKET
            [
                'jenis_id'        => 9,
                'nama_apd'        => 'Life Jacket',
                'kode_apd'        => 'APD-005',
                'deskripsi'       => 'Pelampung keselamatan sesuai standar ISO 12402-5:2020.',
                'gambar'          => 'apd/lifejacket_default.png',
                'bahan'           => 'Nylon + Foam PE',
                'warna'           => 'Orange',
                'ukuran'          => 'All Size (Adjustable)',
                'kemampuan'       => 'Daya apung minimal 50 Newton.',
                'fungsi'          => 'Melindungi pekerja dari tenggelam saat bekerja di area air.',
                'standar'         => 'ISO 12402-5:2020',
                'masa_penggunaan' => '5 tahun',
                'created_by'      => 1,
                'updated_by'      => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
        ]);
    }
}